apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://vm-monitor:9090
    isDefault: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://vm-metrics:8086
    database: vm-metrics
